name: create-release

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

jobs:

  create-release:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Generate rules
        run: |
          mkdir release
          cd release
          ../generate.sh
          sha256sum -- * > SHA256SUMS

      - name: Fail if the artifacts are too big
        run: |
          cd release
          ok=true
          max_size=$(( 20 * 1024 * 1024 )) && echo "max-size: $max_size"
          for file in *; do
            size=$(stat --format=%s -- "$file") && echo "$file: $size"
            [[ $size -gt $max_size ]] && ok=false && echo "$file exceeds max-size"
          done
          [[ $ok == true ]]

      - name: Create release
        run: |
          title=$(date --utc '+%Y-%m-%d')
          note=$(date --utc '+%F %T %Z')
          tag=$(date --utc '+%Y%m%d%H%M%S')
          gh release create --title="$title" --notes="$note" -- "$tag" release/*
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Delete old releases
        run: |
          jq="sort_by(.published_at) | .[:-$KEEP] | .[] | .tag_name"
          extra_tags=$(gh api --paginate --jq="$jq" "repos/$REPO/releases")
          for tag in $extra_tags; do
            echo "deleting release $tag"
            gh release delete --cleanup-tag -- "$tag"
          done
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
          KEEP: 7
