name: create-release

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

jobs:

  create-release:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate rules
        run: |
          mkdir release
          cd release
          ../generate.sh

      - name: Set variables
        run: |
          echo "TAG_NAME=$(date --utc '+%Y%m%d%H%M%S')" >> "$GITHUB_ENV"
          echo "RELEASE_NAME=$(date --utc '+%Y-%m-%d')" >> "$GITHUB_ENV"
          echo "RELEASE_DATE=$(date --utc '+%F %T %Z')" >> "$GITHUB_ENV"

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.RELEASE_NAME }}
          body: ${{ env.RELEASE_DATE }}
          tag: ${{ env.TAG_NAME }}
          artifacts: release/*

      - name: Delete old releases
        run: |
          jq="sort_by(.published_at) | .[:-$KEEP] | .[] | .tag_name"
          extra_tags=$(gh api --paginate --jq="$jq" "repos/$REPO/releases")
          for tag in $extra_tags; do
            echo "deleting release $tag"
            gh release delete --cleanup-tag -- "$tag"
          done
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
          KEEP: 7
