name: gha-keepalive

on:
  schedule:
    - cron: '30 1 * * *'

jobs:

  gha-keepalive:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all branches

      - name: Keep GitHub cron jobs alive using dummy commits
        run: |

          branch=github-actions-keepalive
          wanted_days_since=45

          now=$(date +%s)
          last_commit=$(git log --all --format=%ct --max-count=1)
          actual_days_since=$(( ( now - last_commit ) / ( 60 * 60 * 24 ) ))

          echo "wanted days since last commit: $wanted_days_since"
          echo "actual days since last commit: $actual_days_since"

          if [ "$actual_days_since" -lt "$wanted_days_since" ]; then
            echo 'nothing to do.'
            exit
          fi

          echo 'creating keepalive commit...'

          git config user.name 'github-actions'
          git config user.email 'actions@github.com'

          if git branch --remotes | awk '{ print $1 }' | grep -Fxq "origin/$branch"; then
            git checkout "$branch"
          else
            git checkout --orphan "$branch"
            git rm -rf . ||:
          fi

          git commit --allow-empty --message='github actions keepalive commit'
          git push origin "$branch"
